### ISSUE TITLE
Create server.py File

### ISSUE THREAD

**Issue by sfloam** [devopsdelta/recommendations#17]
**As a** ...  developer
**I need** ...  to organize my RESTful API service
**So that** ...  I can easily test all of my requests from one entry point.

**Assumptions:** 
*...For get requests, it will be /recommendations/id
*...For put requests, it will be /recommendations/id
*...For post requests, it will be /recommendations
*...For list (a get request that gets all recommendations) requests, it will be /recommendations
*...For delete requests, it will be/recommendations/id

**Acceptance Criteria:**
```
Given ... If we run python server.py,
When ...When we browse via local host
Then ... we will automatically be able to run each request seamlessly and view the results of this action. 
```

**Comment by sfloam** [comment]
We need to modify hari's files to remove the URLs
We need to add urls in the server.py file

**Comment by sfloam** [comment]
@cfnyu is this going to replace @Harivadhana Skeleton branch? If so, should we squash it?

**Comment by cfnyu** [comment]
Well I'm not sure we will need individual files for each API call as I don't believe the code will be that lengthy or complicated. I feel most calls made from the API will just be calling either the product class or the models class but the calls themselves won't have much logic in them. For these reasons I think for now we can remove this PR but maybe keep the branch so that if we do decide to use individual files we'll have the branch with the code.

**Comment by sfloam** [comment]
@cfnyu by this PR, do you mean Hari's?

**Comment by cfnyu** [comment]
Yes I meant Hari's PR
